version: "3.9"  # Specify the version of Docker Compose

services:
  app:
    image: node:16  # Node.js base image
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app  # Mount local code to the container
    ports:
      - "3000:3000"  # Expose the app on port 3000
    command: "npm start"  # Command to start the Node.js app
    depends_on:
      - db  # Ensure the database is running before the app starts
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: my_database

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"  # Expose MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql  # Persist database data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose HTTP on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
    depends_on:
      - app  # Ensure the app is running before starting NGINX

volumes:
  db_data:  # Volume for persisting database data
